name: preview compile
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: main
    
    - name: Build
      run: cd website && npm run build
