name: preview compile
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        ref: main
        
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
          
    - name: Build
      run: cd website && npm install && npm run build
